version: '3.9'
services:
  test-db:
    container_name: pg_container
    build:
      context: ./
      dockerfile: .docker/db.dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test-db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/posgresql/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - '5050:80'
volumes:
  pg_data:
